keywords = [
    "LGBTQ+",
    "LGBTQIA+",
    "LGBTQ",
    "LGBT",
    "gay rights",
    "gay",
    "lesbian",
    "bisexual",
    "same-sex",
    "polyamorous",
    "polyamory",
    "polyamorist",
    "polyamorists",
    "transgender rights",
    "transgender",
    "bisexual",
    "lesbian",
    "gender identity",
    "sexual orientation",
    "homophobia",
    "transphobia",
    "gender nonconforming",
    "non-binary",
    "genderqueer",
    "intersex",
    "same-sex marriage",
    "civil union",
    "domestic partnership",
    "gender-affirming surgery",
    "gender dysphoria",
    "two-spirit",
    "LGBTQ health",
    "LGBTQ adoption",
    "LGBTQ military service",
    "LGBTQ discrimination",
    "LGBTQ education",
    "LGBTQ bullying",
    "LGBTQ mental health",
    "LGBTQ HIV/AIDS",
    "LGBTQ community",
    "LGBTQ representation",
    "trans medical care",
    "gender-affirming care",
    "trans healthcare",
    "trans youth healthcare",
    "puberty blockers",
    "hormone blockers",
    "medical transition",
    "transgender athletes",
    "trans sports participation",
    "bathroom bill",
    "gender-neutral restroom",
    "trans youth rights",
    "conversion therapy",
    "gender counseling",
    "gender marker",
    "legal gender change",
    "trans rights",
    "trans discrimination",
    "gender identity protection",
    "gender expression protection",
    "trans employment rights",
    "trans hate crimes",
    "trans military ban",
    "trans inclusive policies",
    "trans education rights",
    "gender-affirming procedures",
    "trans surgeries",
    "trans exclusion policies",
    "trans youth support",
    "trans youth legal rights",
    "trans youth medical rights",
    "trans youth legal protection",
    "trans youth medical protection",
    "trans youth education rights",
    "sexual minority",
    "hate crime legislation",
    "inclusive curriculum",
    "LGBTQ+ ally",
    "LGBTQ+ activism",
    "LGBTQ+ equality",
    "LGBTQ+ legislation",
    "sexual and gender minorities",
    "affirming spaces",
    "homosexual",
    "gender spectrum",
    "queer spaces",
    "queer communities",
    "gay pride",
    "trans pride",
    "bi pride",
    "pride month",
    "sexual diversity",
    "gender diversity",
    "transgender healthcare",
    "queer youth organizations",
    "gender expression",
    "heteronormativity",
    "cisnormativity",
    "sexual equality",
    "queer theory",
    "safe spaces",
    "LGBTQ+ wellness",
    "queer wellness",
    "gender wellness",
    "gender pronouns",
    "gender transition",
    "transitioning",
    "LGBTQ+ rights",
    "LGBTQ+ policies",
    "LGBTQ+ inclusion",
    "sexual identity",
    "gender identity disorder", # historical/medical term
    "sexual minorities",
    "gender minorities",
    "queer identity",
    "gay community",
    "lesbian community",
    "bisexual community",
    "trans community",
    "intersectionality",
    "LGBTQ+ representation in media",
    "LGBTQ+ representation in politics",
    "domestic partner benefits",
    "safe schools",
    "inclusive workplaces",
    "healthcare equity",
    "HIV prevention",
    "PrEP",
    "gender-affirming therapy",
    "gender reassignment",
    "social transition",
    "gender inclusivity",
    "gender-neutral language",
    "sexual orientation non-discrimination",
    "gender identity non-discrimination",
    "queer studies",
    "queer theory",
    "queer representation",
    "queer rights",
    "queer healthcare",
    "queer youth support",
    "queer community support",
    "queer legal protection",
    "queer education rights",
    "queer mental health",
    "queer activism",
    "queer history",
    "queer culture",
    "queer literature",
    "queer arts",
    "queer media",
    "queer film",
    "queer television",
    "queer music",
    "queer sports",
    "queer religion",
    "queer spirituality",
    "queer religious leaders",
    "queer religious history",
    "queer religious rites",
    "queer religious texts",
    "queer theology",
    "queer clergy",
    "queer churches",
    "queer synagogues",
    "queer mosques",
    "queer temples",
    "queer saints",
    "queer religious inclusion",
    "queer religious acceptance",
    "queer religious discrimination",
    "Equality Act",
    "Matthew Shepard Act",
    "Don't Ask, Don't Tell Repeal Act",
    "Defense of Marriage Act",
    "Employment Non-Discrimination Act",
    "sexual preference" # often considered a derogatory term now, but might be in older legislation
    "homosexual acts",
    "sexual reassignment surgery",
    "gender confirmation surgery",
    "sexual minority groups",
    "gender variance",
    "gender non-conforming",
    "queer liberation",
    "queer solidarity",
    "queer activism",
    "queer advocacy",
    "queer rights",
    "queer representation",
    "queer media",
    "Section 377", # Referring to the law criminalizing homosexual acts in India, could be mentioned in international contexts
    "Pink Dot", # LGBTQ+ movement in Singapore
    "ARCIGAY", # Italian LGBTQ+ organization
    "Cogam", # Spanish LGBTQ+ organization
    "homophile", # An older term that was used before 'homosexual' and 'LGBTQ+' became prevalent
    "SOGIE", # Sexual Orientation, Gender Identity, and Expression - often used in policy and international discussions
    "Section 28", # UK legislation that restricted "promotion" of homosexuality in schools
    "Rainbow Railroad", # A Canadian organization helping LGBTQ+ people escape violence and persecution
    "Rainbow Refugees", # A Canadian organization helping LGBTQ+ people escape violence and persecution
    "Rainbow Railroad Canada", # A Canadian organization helping LGBTQ+ people escape violence and persecution
    ]
