"""empty message

Revision ID: 00508c0ab87c
Revises: f7a4b8320017
Create Date: 2023-09-10 01:16:13.883324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00508c0ab87c'
down_revision = 'f7a4b8320017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veto_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('president', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('veto_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veto_message_bill_id'), ['bill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veto_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veto_message_bill_id'))

    op.drop_table('veto_message')
    # ### end Alembic commands ###
