"""empty message

Revision ID: 0b67d03a3467
Revises: cc164bfb013e
Create Date: 2023-09-16 01:19:02.848294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b67d03a3467'
down_revision = 'cc164bfb013e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('co_sponsor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsorship_withdrawn_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_original_cosponsor', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('co_sponsor', schema=None) as batch_op:
        batch_op.drop_column('is_original_cosponsor')
        batch_op.drop_column('sponsorship_withdrawn_date')

    # ### end Alembic commands ###
