"""empty message

Revision ID: 23f519c845db
Revises: b8d7864a171e
Create Date: 2023-09-03 12:06:44.584793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f519c845db'
down_revision = 'b8d7864a171e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('committee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('chamber', sa.String(length=50), nullable=False),
    sa.Column('committee_code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('committee_code')
    )
    op.create_table('politician',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('party', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('profile_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('title_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('date_introduced', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('sponsor_name', sa.String(length=200), nullable=False),
    sa.Column('committee', sa.String(length=200), nullable=True),
    sa.Column('voting_record', sa.Text(), nullable=True),
    sa.Column('full_text_link', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('last_action_date', sa.Date(), nullable=True),
    sa.Column('last_action_description', sa.Text(), nullable=True),
    sa.Column('congress', sa.String(length=50), nullable=True),
    sa.Column('bill_type', sa.String(length=50), nullable=True),
    sa.Column('action_type_id', sa.Integer(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('title_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_type_id'], ['action_type.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['politician.id'], ),
    sa.ForeignKeyConstraint(['title_type_id'], ['title_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_number')
    )
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chamber', sa.String(length=50), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('action_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_type_id'], ['action_type.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amendment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amendment_number', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_proposed', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_committee',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'committee_id')
    )
    op.create_table('bill_subject',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'subject_id')
    )
    op.create_table('co_sponsor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['politician_id'], ['politician.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loc_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_code', sa.String(length=50), nullable=False),
    sa.Column('chamber', sa.String(length=50), nullable=True),
    sa.Column('action_description', sa.String(length=200), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related_bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('related_bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['related_bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_bill')
    op.drop_table('loc_summary')
    op.drop_table('co_sponsor')
    op.drop_table('bill_subject')
    op.drop_table('bill_committee')
    op.drop_table('amendment')
    op.drop_table('action')
    op.drop_table('bill')
    op.drop_table('title_type')
    op.drop_table('subject')
    op.drop_table('politician')
    op.drop_table('committee')
    op.drop_table('action_type')
    # ### end Alembic commands ###
