"""empty message

Revision ID: 273741cce683
Revises: 7b4e3b13179c
Create Date: 2023-09-01 13:41:09.979157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273741cce683'
down_revision = '7b4e3b13179c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amendment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('amendment_Bill_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bill', ['bill_id'], ['id'])
        batch_op.drop_column('Bill_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amendment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Bill_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('amendment_Bill_id_fkey', 'bill', ['Bill_id'], ['id'])
        batch_op.drop_column('bill_id')

    # ### end Alembic commands ###
