"""empty message

Revision ID: 2e1adc9f1ddb
Revises: e45a131e3bc6
Create Date: 2023-09-20 18:23:39.285976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1adc9f1ddb'
down_revision = 'e45a131e3bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veto_message', schema=None) as batch_op:
        batch_op.drop_index('ix_veto_message_bill_id')

    op.drop_table('veto_message')
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yea_votes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nay_votes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('record_vote_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('action_type', schema=None) as batch_op:
        batch_op.drop_column('is_latest')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_latest', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_column('record_vote_number')
        batch_op.drop_column('nay_votes')
        batch_op.drop_column('yea_votes')

    op.create_table('veto_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('president', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], name='veto_message_bill_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='veto_message_pkey')
    )
    with op.batch_alter_table('veto_message', schema=None) as batch_op:
        batch_op.create_index('ix_veto_message_bill_id', ['bill_id'], unique=False)

    # ### end Alembic commands ###
