"""empty message

Revision ID: 30134b5f881c
Revises: adc4c6b2e0cf
Create Date: 2023-09-16 21:33:44.603008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30134b5f881c'
down_revision = 'adc4c6b2e0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('related_bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('congress', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('number', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('latest_action_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('latest_action_text', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('related_bill', schema=None) as batch_op:
        batch_op.drop_column('latest_action_text')
        batch_op.drop_column('latest_action_date')
        batch_op.drop_column('type')
        batch_op.drop_column('number')
        batch_op.drop_column('congress')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
