"""empty message

Revision ID: 55646eba1476
Revises: ddbb2d15d573
Create Date: 2023-09-15 20:53:11.971989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55646eba1476'
down_revision = 'ddbb2d15d573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loc_summary_codes_association',
    sa.Column('loc_summary_id', sa.Integer(), nullable=False),
    sa.Column('loc_summary_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loc_summary_code_id'], ['loc_summary_code.id'], ),
    sa.ForeignKeyConstraint(['loc_summary_id'], ['loc_summary.id'], ),
    sa.PrimaryKeyConstraint('loc_summary_id', 'loc_summary_code_id')
    )
    with op.batch_alter_table('loc_summary_code', schema=None) as batch_op:
        batch_op.drop_constraint('loc_summary_code_loc_summary_id_fkey', type_='foreignkey')
        batch_op.drop_column('loc_summary_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loc_summary_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loc_summary_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('loc_summary_code_loc_summary_id_fkey', 'loc_summary', ['loc_summary_id'], ['id'])

    op.drop_table('loc_summary_codes_association')
    # ### end Alembic commands ###
