"""empty message

Revision ID: 5cbd9dc1a099
Revises: ce711ffb621a
Create Date: 2023-09-20 13:05:49.891167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbd9dc1a099'
down_revision = 'ce711ffb621a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_index('ix_bill_bill_number')
        batch_op.create_index(batch_op.f('ix_bill_bill_number'), ['bill_number'], unique=False)
        batch_op.create_unique_constraint('uc_bill_congress', ['bill_number', 'congress'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_constraint('uc_bill_congress', type_='unique')
        batch_op.drop_index(batch_op.f('ix_bill_bill_number'))
        batch_op.create_index('ix_bill_bill_number', ['bill_number'], unique=False)

    # ### end Alembic commands ###
