"""empty message

Revision ID: 66374ed60fed
Revises: 7be0738dbafa
Create Date: 2023-09-15 19:43:19.019919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66374ed60fed'
down_revision = '7be0738dbafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loc_summary', schema=None) as batch_op:
        batch_op.alter_column('bill_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loc_summary', schema=None) as batch_op:
        batch_op.alter_column('bill_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
