"""empty message

Revision ID: 673051056698
Revises: ac0be4fbdd8e
Create Date: 2023-09-15 19:06:22.161282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673051056698'
down_revision = 'ac0be4fbdd8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('title_type', sa.String(length=2), nullable=False),
    sa.Column('title_text', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_title')
    # ### end Alembic commands ###
