"""empty message

Revision ID: 6d9b45dd19ed
Revises: 30134b5f881c
Create Date: 2023-09-16 21:40:51.081029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9b45dd19ed'
down_revision = '30134b5f881c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('related_bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('relationship_identified_by', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('related_bill', schema=None) as batch_op:
        batch_op.drop_column('relationship_identified_by')
        batch_op.drop_column('relationship_type')

    # ### end Alembic commands ###
