"""empty message

Revision ID: 6eb505e65f00
Revises: 84cc90412393
Create Date: 2023-09-10 02:24:56.041136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb505e65f00'
down_revision = '84cc90412393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('title_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('bill_text_version_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bill_text_version_code', sa.String(), nullable=True))
        batch_op.drop_constraint('title_type_code_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_title_type_id'), ['id'], unique=False)
        batch_op.create_foreign_key(None, 'bill', ['bill_id'], ['id'])
        batch_op.drop_column('code')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_title_type_id'))
        batch_op.create_unique_constraint('title_type_code_key', ['code'])
        batch_op.drop_column('bill_text_version_code')
        batch_op.drop_column('bill_text_version_name')
        batch_op.drop_column('title')
        batch_op.drop_column('title_type')
        batch_op.drop_column('bill_id')

    # ### end Alembic commands ###
