"""empty message

Revision ID: 7136cbeab42e
Revises: 7a677a1bec79
Create Date: 2023-09-17 11:56:06.823816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7136cbeab42e'
down_revision = '7a677a1bec79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('related_bill', schema=None) as batch_op:
        batch_op.alter_column('related_bill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('related_bill_related_bill_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('related_bill', schema=None) as batch_op:
        batch_op.create_foreign_key('related_bill_related_bill_id_fkey', 'bill', ['related_bill_id'], ['id'])
        batch_op.alter_column('related_bill_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
