"""empty message

Revision ID: 7a677a1bec79
Revises: 4f9a656a05ef
Create Date: 2023-09-17 01:09:52.734834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a677a1bec79'
down_revision = '4f9a656a05ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politician', schema=None) as batch_op:
        batch_op.drop_column('lis_id')
        batch_op.drop_column('gpo_id')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gpo_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lis_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
