"""empty message

Revision ID: 7b4e3b13179c
Revises: 852c7f5b7b04
Create Date: 2023-09-01 13:39:32.884345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4e3b13179c'
down_revision = '852c7f5b7b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('action_Bill_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bill', ['bill_id'], ['id'])
        batch_op.drop_column('Bill_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Bill_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('action_Bill_id_fkey', 'bill', ['Bill_id'], ['id'])
        batch_op.drop_column('bill_id')

    # ### end Alembic commands ###
