"""empty message

Revision ID: 7d016c53d156
Revises: 2a6f1ca2135e
Create Date: 2023-09-11 13:01:18.126817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d016c53d156'
down_revision = '2a6f1ca2135e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('law',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('law', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_law_bill_id'), ['bill_id'], unique=False)

    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_bill_id'), ['bill_id'], unique=False)

    op.create_table('recorded_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamber', sa.String(length=50), nullable=True),
    sa.Column('congress', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('full_action_name', sa.String(length=200), nullable=True),
    sa.Column('roll_number', sa.String(length=50), nullable=True),
    sa.Column('session_number', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recorded_vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recorded_vote_bill_id'), ['bill_id'], unique=False)

    with op.batch_alter_table('title_type', schema=None) as batch_op:
        batch_op.drop_index('ix_title_type_id')

    op.drop_table('title_type')
    with op.batch_alter_table('action_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_type', sa.Enum('TYPE1', 'TYPE2', 'TYPE3'), nullable=False))

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('official_title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('origin_chamber', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('primary_subject_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('bill_title_type_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subject', ['primary_subject_id'], ['id'])
        batch_op.drop_column('title_type_id')

    with op.batch_alter_table('loc_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('as_enacted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('as_introduced', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('as_passed_house', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('as_passed_senate', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('as_reported_to_house', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('as_reported_to_senate', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('latest_major_action', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('latest_summary', sa.Text(), nullable=True))

    with op.batch_alter_table('politician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('middle_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bioguide_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gpo_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lis_id', sa.String(length=50), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('politician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('lis_id')
        batch_op.drop_column('gpo_id')
        batch_op.drop_column('bioguide_id')
        batch_op.drop_column('last_name')
        batch_op.drop_column('middle_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('loc_summary', schema=None) as batch_op:
        batch_op.drop_column('latest_summary')
        batch_op.drop_column('latest_major_action')
        batch_op.drop_column('as_reported_to_senate')
        batch_op.drop_column('as_reported_to_house')
        batch_op.drop_column('as_passed_senate')
        batch_op.drop_column('as_passed_house')
        batch_op.drop_column('as_introduced')
        batch_op.drop_column('as_enacted')

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bill_title_type_id_fkey', 'title_type', ['title_type_id'], ['id'])
        batch_op.drop_column('primary_subject_id')
        batch_op.drop_column('origin_chamber')
        batch_op.drop_column('official_title')

    with op.batch_alter_table('action_type', schema=None) as batch_op:
        batch_op.drop_column('action_type')

    op.create_table('title_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bill_text_version_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bill_text_version_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], name='title_type_bill_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='title_type_pkey')
    )
    with op.batch_alter_table('title_type', schema=None) as batch_op:
        batch_op.create_index('ix_title_type_id', ['id'], unique=False)

    with op.batch_alter_table('recorded_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recorded_vote_bill_id'))

    op.drop_table('recorded_vote')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_bill_id'))

    op.drop_table('note')
    with op.batch_alter_table('law', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_law_bill_id'))

    op.drop_table('law')
    # ### end Alembic commands ###
