"""empty message

Revision ID: 7d77a7f2f7af
Revises: 0b67d03a3467
Create Date: 2023-09-16 01:23:54.935218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d77a7f2f7af'
down_revision = '0b67d03a3467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_title', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chamber_code', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_title', schema=None) as batch_op:
        batch_op.drop_column('chamber_code')

    # ### end Alembic commands ###
