"""empty message

Revision ID: 7ed7d497004a
Revises: 2558ab833231
Create Date: 2023-09-01 21:57:59.432527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed7d497004a'
down_revision = '2558ab833231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_constraint('bill_loc_summary_id_fkey', type_='foreignkey')
        batch_op.drop_column('loc_summary_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loc_summary_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('bill_loc_summary_id_fkey', 'loc_summary', ['loc_summary_id'], ['id'])

    # ### end Alembic commands ###
