"""empty message

Revision ID: 852c7f5b7b04
Revises: 6c5fcc2f76af
Create Date: 2023-09-01 13:27:19.000845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852c7f5b7b04'
down_revision = '6c5fcc2f76af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loc_summary_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'loc_summary', ['loc_summary_id'], ['id'])
        batch_op.create_foreign_key(None, 'action_type', ['action_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('loc_summary_id')
        batch_op.drop_column('action_type_id')

    # ### end Alembic commands ###
