"""Added new models

Revision ID: 85921e097229
Revises: 
Create Date: 2023-08-29 23:31:22.528964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85921e097229'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('politician',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('party', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('profile_link', sa.String(length=500), nullable=True),
    sa.Column('sponsored_bill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sponsored_bill_id'], ['legislation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related_bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislation_id', sa.Integer(), nullable=False),
    sa.Column('related_bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], ),
    sa.ForeignKeyConstraint(['related_bill_id'], ['legislation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co_sponsor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislation_id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], ),
    sa.ForeignKeyConstraint(['politician_id'], ['politician.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legislation', schema=None) as batch_op:
        batch_op.drop_column('co_sponsors')
        batch_op.drop_column('related_bills')
        batch_op.drop_column('sponsor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legislation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsor', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('related_bills', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('co_sponsors', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('co_sponsor')
    op.drop_table('related_bill')
    op.drop_table('politician')
    # ### end Alembic commands ###
