"""empty message

Revision ID: a0a439829a3e
Revises: 66374ed60fed
Create Date: 2023-09-15 19:57:46.715581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a439829a3e'
down_revision = '66374ed60fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loc_summary_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loc_summary_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'loc_summary', ['loc_summary_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loc_summary_code', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('loc_summary_id')

    # ### end Alembic commands ###
