"""empty message

Revision ID: cc164bfb013e
Revises: 412aec2b1220
Create Date: 2023-09-15 22:49:41.991083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc164bfb013e'
down_revision = '412aec2b1220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loc_summary_association', schema=None) as batch_op:
        batch_op.alter_column('loc_summary_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('loc_summary_code_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loc_summary_association', schema=None) as batch_op:
        batch_op.alter_column('loc_summary_code_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('loc_summary_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
