"""empty message

Revision ID: ce711ffb621a
Revises: 
Create Date: 2023-09-20 01:01:05.741871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce711ffb621a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('committee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('chamber', sa.String(length=255), nullable=False),
    sa.Column('committee_code', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('committee_code')
    )
    op.create_table('loc_summary_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamber', sa.String(), nullable=False),
    sa.Column('version_code', sa.String(), nullable=False),
    sa.Column('action_desc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_code')
    )
    op.create_table('politician',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('bioguide_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('profile_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(), nullable=False),
    sa.Column('date_introduced', sa.Date(), nullable=False),
    sa.Column('origin_chamber', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('bill_type', sa.String(), nullable=True),
    sa.Column('congress', sa.String(), nullable=True),
    sa.Column('committee', sa.String(), nullable=True),
    sa.Column('last_action_date', sa.Date(), nullable=True),
    sa.Column('last_action_description', sa.Text(), nullable=True),
    sa.Column('update_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('full_bill_link', sa.String(), nullable=True),
    sa.Column('voting_record', sa.Text(), nullable=True),
    sa.Column('xml_content', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('action_type_id', sa.Integer(), nullable=True),
    sa.Column('primary_subject_id', sa.Integer(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_type_id'], ['action_type.id'], ),
    sa.ForeignKeyConstraint(['primary_subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['politician.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_bill_number'), ['bill_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_bill_tags'), ['tags'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_title'), ['title'], unique=False)

    op.create_table('subcommittee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('subcommittee_code', sa.String(length=255), nullable=False),
    sa.Column('activity_name', sa.String(length=1000), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subcommittee_code')
    )
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('chamber', sa.Text(), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('action_type_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['action_type_id'], ['action_type.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_action_type_id'), ['action_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_bill_id'), ['bill_id'], unique=False)

    op.create_table('amendment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amendment_number', sa.String(), nullable=False),
    sa.Column('congress', sa.String(), nullable=True),
    sa.Column('latest_action_date', sa.Date(), nullable=True),
    sa.Column('latest_action_text', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['politician.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('amendment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amendment_bill_id'), ['bill_id'], unique=False)

    op.create_table('bill_committee',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'committee_id')
    )
    op.create_table('bill_full_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('bill_metadata', sa.JSON(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('parsing_status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill_full_text', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_full_text_bill_id'), ['bill_id'], unique=False)

    op.create_table('bill_subcommittee',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('subcommittee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['subcommittee_id'], ['subcommittee.id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'subcommittee_id')
    )
    op.create_table('bill_subject',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'subject_id')
    )
    with op.batch_alter_table('bill_subject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_subject_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_subject_subject_id'), ['subject_id'], unique=False)

    op.create_table('bill_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('title_type', sa.String(), nullable=False),
    sa.Column('title_text', sa.String(), nullable=False),
    sa.Column('chamber_code', sa.String(), nullable=True),
    sa.Column('chamber_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co_sponsor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('sponsorship_date', sa.Date(), nullable=True),
    sa.Column('is_original_cosponsor', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sponsorship_withdrawn_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['politician_id'], ['politician.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('co_sponsor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_co_sponsor_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_co_sponsor_politician_id'), ['politician_id'], unique=False)

    op.create_table('law',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('law', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_law_bill_id'), ['bill_id'], unique=False)

    op.create_table('loc_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_code', sa.String(), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('action_desc', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loc_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loc_summary_update_date'), ['update_date'], unique=False)

    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_bill_id'), ['bill_id'], unique=False)

    op.create_table('policy_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_area', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_area_bill_id'), ['bill_id'], unique=False)

    op.create_table('recorded_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamber', sa.String(), nullable=True),
    sa.Column('congress', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('full_action_name', sa.String(), nullable=True),
    sa.Column('roll_number', sa.String(), nullable=True),
    sa.Column('session_number', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recorded_vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recorded_vote_bill_id'), ['bill_id'], unique=False)

    op.create_table('related_bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('congress', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('action_text', sa.String(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('identified_by', sa.String(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veto_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('president', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('veto_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veto_message_bill_id'), ['bill_id'], unique=False)

    op.create_table('action_actioncode',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('action_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_code_id'], ['action_code.id'], ),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.PrimaryKeyConstraint('action_id', 'action_code_id')
    )
    op.create_table('amended_bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('congress', sa.String(), nullable=True),
    sa.Column('origin_chamber', sa.String(), nullable=True),
    sa.Column('origin_chamber_code', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('amendment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amendment_id'], ['amendment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amendment_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_code', sa.String(), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('action_time', sa.String(), nullable=True),
    sa.Column('committee_name', sa.String(), nullable=True),
    sa.Column('committee_system_code', sa.String(), nullable=True),
    sa.Column('action_text', sa.Text(), nullable=True),
    sa.Column('amendment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amendment_id'], ['amendment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amendment_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('amendment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amendment_id'], ['amendment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('identified_by', sa.String(), nullable=True),
    sa.Column('related_bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['related_bill_id'], ['related_bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loc_summary_association',
    sa.Column('loc_summary_id', sa.Integer(), nullable=False),
    sa.Column('loc_summary_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loc_summary_code_id'], ['loc_summary_code.id'], ),
    sa.ForeignKeyConstraint(['loc_summary_id'], ['loc_summary.id'], ),
    sa.PrimaryKeyConstraint('loc_summary_id', 'loc_summary_code_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loc_summary_association')
    op.drop_table('bill_relationship')
    op.drop_table('amendment_link')
    op.drop_table('amendment_action')
    op.drop_table('amended_bill')
    op.drop_table('action_actioncode')
    with op.batch_alter_table('veto_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veto_message_bill_id'))

    op.drop_table('veto_message')
    op.drop_table('related_bill')
    with op.batch_alter_table('recorded_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recorded_vote_bill_id'))

    op.drop_table('recorded_vote')
    with op.batch_alter_table('policy_area', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_area_bill_id'))

    op.drop_table('policy_area')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_bill_id'))

    op.drop_table('note')
    with op.batch_alter_table('loc_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loc_summary_update_date'))

    op.drop_table('loc_summary')
    with op.batch_alter_table('law', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_law_bill_id'))

    op.drop_table('law')
    with op.batch_alter_table('co_sponsor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_co_sponsor_politician_id'))
        batch_op.drop_index(batch_op.f('ix_co_sponsor_bill_id'))

    op.drop_table('co_sponsor')
    op.drop_table('bill_title')
    with op.batch_alter_table('bill_subject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_subject_subject_id'))
        batch_op.drop_index(batch_op.f('ix_bill_subject_bill_id'))

    op.drop_table('bill_subject')
    op.drop_table('bill_subcommittee')
    with op.batch_alter_table('bill_full_text', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_full_text_bill_id'))

    op.drop_table('bill_full_text')
    op.drop_table('bill_committee')
    with op.batch_alter_table('amendment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amendment_bill_id'))

    op.drop_table('amendment')
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_bill_id'))
        batch_op.drop_index(batch_op.f('ix_action_action_type_id'))

    op.drop_table('action')
    op.drop_table('subcommittee')
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_title'))
        batch_op.drop_index(batch_op.f('ix_bill_tags'))
        batch_op.drop_index(batch_op.f('ix_bill_bill_number'))

    op.drop_table('bill')
    op.drop_table('subject')
    op.drop_table('politician')
    op.drop_table('loc_summary_code')
    op.drop_table('committee')
    op.drop_table('action_type')
    op.drop_table('action_code')
    # ### end Alembic commands ###
