"""empty message

Revision ID: d693425f86b5
Revises: 7136cbeab42e
Create Date: 2023-09-17 13:18:25.077599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd693425f86b5'
down_revision = '7136cbeab42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('related_bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_bill_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('related_bill_number', sa.String(), nullable=False))
        batch_op.drop_index('ix_related_bill_bill_id')
        batch_op.drop_index('ix_related_bill_related_bill_id')
        batch_op.create_index(batch_op.f('ix_related_bill_main_bill_id'), ['main_bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_related_bill_related_bill_number'), ['related_bill_number'], unique=False)
        batch_op.drop_constraint('related_bill_bill_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bill', ['main_bill_id'], ['id'])
        batch_op.drop_column('bill_id')
        batch_op.drop_column('related_bill_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('related_bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_bill_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('related_bill_bill_id_fkey', 'bill', ['bill_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_related_bill_related_bill_number'))
        batch_op.drop_index(batch_op.f('ix_related_bill_main_bill_id'))
        batch_op.create_index('ix_related_bill_related_bill_id', ['related_bill_id'], unique=False)
        batch_op.create_index('ix_related_bill_bill_id', ['bill_id'], unique=False)
        batch_op.drop_column('related_bill_number')
        batch_op.drop_column('main_bill_id')

    # ### end Alembic commands ###
