"""empty message

Revision ID: dcb0fd2d00b5
Revises: 0e70bafd98b6
Create Date: 2023-09-22 02:46:40.239030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb0fd2d00b5'
down_revision = '0e70bafd98b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_constraint('bill_sponsor_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('bill_primary_subject_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('bill_action_type_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subject', ['primary_subject_id'], ['id'])
        batch_op.create_foreign_key(None, 'action_type', ['action_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'politician', ['sponsor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bill_action_type_id_fkey', 'action_type', ['action_type_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('bill_primary_subject_id_fkey', 'subject', ['primary_subject_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('bill_sponsor_id_fkey', 'politician', ['sponsor_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
