"""empty message

Revision ID: e4191c4475b5
Revises: dea79e4d23aa
Create Date: 2023-08-31 00:21:29.165372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4191c4475b5'
down_revision = 'dea79e4d23aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('date_introduced', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('sponsor_name', sa.String(length=200), nullable=False),
    sa.Column('committee', sa.String(length=200), nullable=True),
    sa.Column('voting_record', sa.Text(), nullable=True),
    sa.Column('full_text_link', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('last_action_date', sa.Date(), nullable=True),
    sa.Column('last_action_description', sa.Text(), nullable=True),
    sa.Column('congress', sa.String(length=50), nullable=True),
    sa.Column('bill_type', sa.String(length=50), nullable=True),
    sa.Column('action_type_id', sa.Integer(), nullable=True),
    sa.Column('loc_summary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_type_id'], ['action_type.id'], ),
    sa.ForeignKeyConstraint(['loc_summary_id'], ['loc_summary.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_number')
    )
    op.create_table('committee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('chamber', sa.String(length=50), nullable=False),
    sa.Column('committee_code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('committee_code')
    )
    op.create_table('bill_committee',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'committee_id')
    )
    with op.batch_alter_table('co_sponsor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('co_sponsor_legislation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bill', ['bill_id'], ['id'])
        batch_op.drop_column('legislation_id')

    with op.batch_alter_table('loc_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('loc_summary_legislation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bill', ['bill_id'], ['id'])
        batch_op.drop_column('legislation_id')

    with op.batch_alter_table('related_bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('related_bill_related_bill_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('related_bill_legislation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bill', ['related_bill_id'], ['id'])
        batch_op.create_foreign_key(None, 'bill', ['bill_id'], ['id'])
        batch_op.drop_column('legislation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('related_bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legislation_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('related_bill_legislation_id_fkey', 'legislation', ['legislation_id'], ['id'])
        batch_op.create_foreign_key('related_bill_related_bill_id_fkey', 'legislation', ['related_bill_id'], ['id'])
        batch_op.drop_column('bill_id')

    with op.batch_alter_table('loc_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legislation_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('loc_summary_legislation_id_fkey', 'legislation', ['legislation_id'], ['id'])
        batch_op.drop_column('bill_id')

    with op.batch_alter_table('co_sponsor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legislation_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('co_sponsor_legislation_id_fkey', 'legislation', ['legislation_id'], ['id'])
        batch_op.drop_column('bill_id')

    op.create_table('legislation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_introduced', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bill_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('committee', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('voting_record', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('full_text_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('last_action_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('last_action_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('action_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loc_summary_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sponsor_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('congress', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bill_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_type_id'], ['action_type.id'], name='legislation_action_type_id_fkey'),
    sa.ForeignKeyConstraint(['loc_summary_id'], ['loc_summary.id'], name='legislation_loc_summary_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='legislation_pkey'),
    sa.UniqueConstraint('bill_number', name='legislation_bill_number_key')
    )
    op.drop_table('bill_committee')
    op.drop_table('committee')
    op.drop_table('bill')
    # ### end Alembic commands ###
