"""empty message

Revision ID: e45a131e3bc6
Revises: 5cbd9dc1a099
Create Date: 2023-09-20 17:05:29.500342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45a131e3bc6'
down_revision = '5cbd9dc1a099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_constraint('uc_bill_congress', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.create_unique_constraint('uc_bill_congress', ['bill_number', 'congress'])

    # ### end Alembic commands ###
