"""empty message

Revision ID: fcab6c2c9d9e
Revises: 2604804a16e6
Create Date: 2023-09-16 01:51:03.746411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcab6c2c9d9e'
down_revision = '2604804a16e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_title', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chamber_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_title', schema=None) as batch_op:
        batch_op.drop_column('chamber_name')

    # ### end Alembic commands ###
